services:
  app:
    image: mcr.microsoft.com/devcontainers/python:1-3.11-bullseye

  postgres:
    image: postgres:14

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
